spring:
  application:
    name: workers
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.3.14:13306/imj?useSSL=false&allowPublicKeyRetrieval=true
      username: imj
      password: imj
      pool-name: Hikari Connection Pool  # Pool Name Alias
      maximum-pool-size: 3
  jpa:
    database: mysql
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true

server:
  port: 8000  

logging:
  level: 
    root: INFO
    


